
name: Go Build and Run

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        #go-version: '^1.21.3' # Use a valid Go version
        #check-latest: true # 
        go-version-file: '/go.mod'

    - name: Build and Run
      run: go run hello.go
